# Generated by Django 2.1 on 2018-08-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='atlas.Entity'),
        ),
    ]
